version: '3.8'

services:
  backend:
    build: ./backend
    container_name: recommender-backend
    ports:
      - "8000:8000"
    volumes:
      # This volume mapping is for local development.
      # It syncs your local files with the container.
      - ./backend/app:/code/app
      
  frontend:
    build: ./frontend
    container_name: recommender-frontend
    ports:
      - "5173:80" # Map host port 5173 to container's Nginx port 80
    depends_on:
      - backend